=== operon-io/devidemo/src/main/resources/mapforce/worktimeJson.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "person_id",
      "date",
      "arrival_ts",
      "departure_ts",
      "extra_info",
      "code"
    ],
    "additionalProperties": false,
    "properties": {
      "person_id": {
        "type": "string"
      },
      "date": {
        "type": "string"
      },
      "arrival_ts": {
        "type": "string"
      },
      "departure_ts": {
        "type": "string"
      },
      "extra_info": {
        "type": "string"
      },
      "code": {
        "type": "string"
      }
    }
  }
}

=== operon-io/devidemo/outbox/json/test-output.json
[
	{
		"person_id": "45",
		"date": "2022-06-26",
		"arrival_ts": "0852",
		"departure_ts": "0645",
		"extra_info": "0",
		"code": "CHECK"
	},
	{
		"person_id": "37",
		"date": "2022-06-25",
		"arrival_ts": "0656",
		"departure_ts": "0949",
		"extra_info": "0",
		"code": "CHECK"
	}
]
